sudo: required
services:
  - docker

before_install:
  - docker build -t gustavomontesinos/docker-react -f Dockerfile.dev .

script:
  - docker run gustavomontesinos/docker-react npm run test -- --coverage
